language: csharp
solution: ModbusImp.sln
install:
  - nuget restore ModbusImp.sln
  - nuget install NUnit.Runners -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release ModbusImp.sln
  - mono ./testrunner/NUnit.Runners.*/tools/nuint-console.exe ./ModbusImp.Tests/bin/Release/ModbusImp.Tests.dll