# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modbus.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='modbus.proto',
  package='ModbusImp.Service',
  syntax='proto3',
  serialized_pb=_b('\n\x0cmodbus.proto\x12\x11ModbusImp.Service\"Z\n\nTCPRequest\x12\x0f\n\x07slaveId\x18\x01 \x01(\r\x12\x14\n\x0c\x66unctionCode\x18\x02 \x01(\r\x12\x14\n\x0cstartAddress\x18\x03 \x01(\r\x12\x0f\n\x07readCnt\x18\x04 \x01(\r\"\x1a\n\x0bTCPResponse\x12\x0b\n\x03seq\x18\x01 \x01(\t2S\n\x06Modbus\x12I\n\x06GetTCP\x12\x1d.ModbusImp.Service.TCPRequest\x1a\x1e.ModbusImp.Service.TCPResponse\"\x00\x62\x06proto3')
)




_TCPREQUEST = _descriptor.Descriptor(
  name='TCPRequest',
  full_name='ModbusImp.Service.TCPRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='slaveId', full_name='ModbusImp.Service.TCPRequest.slaveId', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='functionCode', full_name='ModbusImp.Service.TCPRequest.functionCode', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='startAddress', full_name='ModbusImp.Service.TCPRequest.startAddress', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='readCnt', full_name='ModbusImp.Service.TCPRequest.readCnt', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=125,
)


_TCPRESPONSE = _descriptor.Descriptor(
  name='TCPResponse',
  full_name='ModbusImp.Service.TCPResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='seq', full_name='ModbusImp.Service.TCPResponse.seq', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=127,
  serialized_end=153,
)

DESCRIPTOR.message_types_by_name['TCPRequest'] = _TCPREQUEST
DESCRIPTOR.message_types_by_name['TCPResponse'] = _TCPRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TCPRequest = _reflection.GeneratedProtocolMessageType('TCPRequest', (_message.Message,), dict(
  DESCRIPTOR = _TCPREQUEST,
  __module__ = 'modbus_pb2'
  # @@protoc_insertion_point(class_scope:ModbusImp.Service.TCPRequest)
  ))
_sym_db.RegisterMessage(TCPRequest)

TCPResponse = _reflection.GeneratedProtocolMessageType('TCPResponse', (_message.Message,), dict(
  DESCRIPTOR = _TCPRESPONSE,
  __module__ = 'modbus_pb2'
  # @@protoc_insertion_point(class_scope:ModbusImp.Service.TCPResponse)
  ))
_sym_db.RegisterMessage(TCPResponse)



_MODBUS = _descriptor.ServiceDescriptor(
  name='Modbus',
  full_name='ModbusImp.Service.Modbus',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=155,
  serialized_end=238,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetTCP',
    full_name='ModbusImp.Service.Modbus.GetTCP',
    index=0,
    containing_service=None,
    input_type=_TCPREQUEST,
    output_type=_TCPRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MODBUS)

DESCRIPTOR.services_by_name['Modbus'] = _MODBUS

# @@protoc_insertion_point(module_scope)
